# Generated by Django 6.0.8 on 2026-08-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_employee_bond_period_employee_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='salary_status',
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('Intern', 'Intern'), ('Trainee', 'Trainee'), ('Full Time', 'Full Time'), ('Part Time', 'Part Time')], default='Intern', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bond_period',
            field=models.CharField(choices=[('No Bond', 'No Bond'), ('120 Hours', '120 Hours'), ('1 Month', '1 Month'), ('3 Months', '3 Months'), ('6 Months', '6 Months'), ('1 Year', '1 Year'), ('2 Years', '2 Years')], default='No Bond', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
