# Generated by Django 6.0.8 on 2026-08-08 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_attendance_check_in_alter_attendance_check_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='created_at',
        ),
    ]
