# Generated by Django 6.0.8 on 2026-08-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='github_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
